global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.122.183:9100']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['192.168.122.183:9104']
