- name: restart mysqld_exporter
  systemd:
    name: mysqld_exporter
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart node_exporter
  systemd:
    name: node_exporter
    daemon_reload: true
    enabled: true
    state: restarted

- name: restart nftables
  systemd:
    name: nftables
    daemon_reload: true
    enabled: true
    state: restarted
