open_ports:
  - 22      # SSH
  - 3306    # MariaDB
  - 9100    # node_exporter
  - 9104    # mysqld_exporter


node_exporter_version: "1.8.1"
mysqld_exporter_version: "0.15.0"

mysqld_exporter_password: "StrongPassword123!"